from snakemake.utils import min_version
from snakemake.utils import validate
import pandas as pd
min_version("7.3.0")


configfile: "config/config.yaml"

include: "rules/demultiplex.smk"
include: "rules/qc.smk"

rule target:
    input:
        expand("output/qc/fastqc/{sample}.{direction}.html", sample=ALL_SAMPLES, direction = ["f", "r"])

